SIMULATION_STEPS = 1000

LATTICE_WIDTH = 256
LATTICE_HEIGHT = 256
LATTICE_SIZE = (LATTICE_WIDTH, LATTICE_HEIGHT)

DENSITY = 0.6

RANDOMIZED = False

DISPLAY_WIDTH = 896
DISPLAY_HEIGHT = 896
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)

DISPLAY_COLOR_1 = (255, 0, 0)  # Display color for horizontally moving vehicles
DISPLAY_COLOR_2 = (0, 0, 255)  # Display color for vertically moving vehicles

SCALE = DISPLAY_WIDTH / LATTICE_WIDTH
